# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rba1988/workspace/research/implementation/slic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rba1988/workspace/research/implementation/slic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rba1988/workspace/research/implementation/slic/CMakeFiles /home/rba1988/workspace/research/implementation/slic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rba1988/workspace/research/implementation/slic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slic

# Build rule for target.
slic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slic
.PHONY : slic

# fast build rule for target.
slic/fast:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/build
.PHONY : slic/fast

#=============================================================================
# Target rules for targets named slicsvmvalidator

# Build rule for target.
slicsvmvalidator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slicsvmvalidator
.PHONY : slicsvmvalidator

# fast build rule for target.
slicsvmvalidator/fast:
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/build
.PHONY : slicsvmvalidator/fast

#=============================================================================
# Target rules for targets named svmtrain

# Build rule for target.
svmtrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 svmtrain
.PHONY : svmtrain

# fast build rule for target.
svmtrain/fast:
	$(MAKE) -f CMakeFiles/svmtrain.dir/build.make CMakeFiles/svmtrain.dir/build
.PHONY : svmtrain/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/main.cpp.s
.PHONY : main.cpp.s

slic.o: slic.cpp.o
.PHONY : slic.o

# target to build an object file
slic.cpp.o:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/slic.cpp.o
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slic.cpp.o
.PHONY : slic.cpp.o

slic.i: slic.cpp.i
.PHONY : slic.i

# target to preprocess a source file
slic.cpp.i:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/slic.cpp.i
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slic.cpp.i
.PHONY : slic.cpp.i

slic.s: slic.cpp.s
.PHONY : slic.s

# target to generate assembly for a file
slic.cpp.s:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/slic.cpp.s
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slic.cpp.s
.PHONY : slic.cpp.s

slicsvmvalidator.o: slicsvmvalidator.cpp.o
.PHONY : slicsvmvalidator.o

# target to build an object file
slicsvmvalidator.cpp.o:
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slicsvmvalidator.cpp.o
.PHONY : slicsvmvalidator.cpp.o

slicsvmvalidator.i: slicsvmvalidator.cpp.i
.PHONY : slicsvmvalidator.i

# target to preprocess a source file
slicsvmvalidator.cpp.i:
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slicsvmvalidator.cpp.i
.PHONY : slicsvmvalidator.cpp.i

slicsvmvalidator.s: slicsvmvalidator.cpp.s
.PHONY : slicsvmvalidator.s

# target to generate assembly for a file
slicsvmvalidator.cpp.s:
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/slicsvmvalidator.cpp.s
.PHONY : slicsvmvalidator.cpp.s

svmtrain.o: svmtrain.cpp.o
.PHONY : svmtrain.o

# target to build an object file
svmtrain.cpp.o:
	$(MAKE) -f CMakeFiles/svmtrain.dir/build.make CMakeFiles/svmtrain.dir/svmtrain.cpp.o
.PHONY : svmtrain.cpp.o

svmtrain.i: svmtrain.cpp.i
.PHONY : svmtrain.i

# target to preprocess a source file
svmtrain.cpp.i:
	$(MAKE) -f CMakeFiles/svmtrain.dir/build.make CMakeFiles/svmtrain.dir/svmtrain.cpp.i
.PHONY : svmtrain.cpp.i

svmtrain.s: svmtrain.cpp.s
.PHONY : svmtrain.s

# target to generate assembly for a file
svmtrain.cpp.s:
	$(MAKE) -f CMakeFiles/svmtrain.dir/build.make CMakeFiles/svmtrain.dir/svmtrain.cpp.s
.PHONY : svmtrain.cpp.s

timer.o: timer.cpp.o
.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/timer.cpp.o
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i
.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/timer.cpp.i
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s
.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/slic.dir/build.make CMakeFiles/slic.dir/timer.cpp.s
	$(MAKE) -f CMakeFiles/slicsvmvalidator.dir/build.make CMakeFiles/slicsvmvalidator.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... slic"
	@echo "... slicsvmvalidator"
	@echo "... svmtrain"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... slic.o"
	@echo "... slic.i"
	@echo "... slic.s"
	@echo "... slicsvmvalidator.o"
	@echo "... slicsvmvalidator.i"
	@echo "... slicsvmvalidator.s"
	@echo "... svmtrain.o"
	@echo "... svmtrain.i"
	@echo "... svmtrain.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

